---

- name: Install Java 8
  become: yes
  apt:
    name: openjdk-8-jre-headless
    state: present
  notify: Restart UniFi controller

#- name: Configure Oracle JDK as default
#  become: yes
#  alternatives:
#    name: java
#    path: "{{ java_oracle_path }}"
#  notify: Restart UniFi controller

- name: Configure the ubnt apt key
  become: yes
  apt_key:
    id: C0A52C50
    keyserver: keyserver.ubuntu.com
    state: present

- name: Configure the ubnt apt repository
  become: yes
  apt_repository:
    repo: 'deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti'
    update_cache: yes
    state: present

- name: Install UniFi controller
  become: yes
  apt:
    name: unifi
    state: present
    allow_unauthenticated: yes
    update_cache: yes
    autoclean: yes
    autoremove: yes
  notify: Restart UniFi controller

- name: Start UniFi controller
  become: yes
  service:
    name: unifi
    state: started
    enabled: yes
